# Generated by Django 5.2 on 2025-04-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('payload', models.TextField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
